### PR TITLE
fix compilation error for static library when lto is enabled

### LINKED ISSUE #714: Build error with sirius@7.2.7, 7.3.0 with gcc@9.4.0 using spack
I am encountering errors like
```console
/tmp/test_srvo3_pwpp.TFS7EC.ltrans64.ltrans.o: In function `sirius::K_point_set::create_k_mesh(geometry3d::vector3d<int>, geometry3d::vector3d<int>, int)':
<artificial>:(.text+0x74d4): undefined reference to `sirius::K_point<double>::generate_gklo_basis()'
collect2: error: ld returned 1 exit status
```
when trying to build sirius@7.2.7 or 7.3.0 using gcc@9.4.0 under spack.
Specifically trying to build in spack
```console
$ spack install sirius@7.2.7%gcc@9.4.0+apps ~boost_filesystem build_type=Release ~cuda ~elpa +fortran +ipo ~magma +memory_pool ~nlcglib +openmp +profiler +python ~rocm +scalapack ~shared ~single_precision +tests +vdwxc
```
using 
```console
$ spack debug report
* **Spack:** 0.17.0-319-5dce4d79bd
* **Python:** 3.6.8
* **Platform:** linux-rhel8-zen2
* **Concretizer:** clingo
```
(I have also updated the package.py for sirius with the copy from the latest devel branch of spack as of 2022-01-05 to try @7.3.0, with the same results).  I have since successfully compiled @7.2.6 with the same setup.  

I am submitting this report to sirius rather than spack as it looks to me like a sirius rather than spack error, and spack is the recommended installation procedure for sirius.

The full build output is:
[spack-build-out.txt](https://github.com/electronic-structure/SIRIUS/files/7815952/spack-build-out.txt)

### PR DESCRIPTION
**Pull request by simonpintarelli**
This should fix #714 . `K_point<T>::generate_gklo_basis` was instantiated in a separate file, while the other member functions of `K_point<T>` were explicitly instatiated in `k_point.cpp`.  This didn't compile with `gcc@9.4.0/11.1.0` and most likely other gcc versions.

### CODE REVIEW

**Comment by toxa81** [comment]
@haampie Harmen, sorry to bother! The CI seems to be broken because gitlab pipeline failed to rebuild the new image(s).

**Comment by haampie** [comment]
I would just ignore the rocm build for now
